#pragma once
#define ID_TEX_JASON 0
#define ID_TEX_ENEMY 10
#define ID_TEX_MISC 20
#define OBJECT_TYPE_JASON	0
#define OBJECT_TYPE_BLACKFOOT	1
#define OBJECT_TYPE_SUNAMI	2
#define OBJECT_TYPE_EYELET	3
#define OBJECT_TYPE_BELLBOMBER	4

#pragma region JASON 
// big
#define ID_SPRITE_JASON 10000
#define ID_SPRITE_JASON_BIG (ID_SPRITE_JASON + 1000)
#define ID_SPRITE_JASON_BIG_IDLE (ID_SPRITE_JASON_BIG + 100)
#define ID_SPRITE_JASON_BIG_IDLE_LEFT (ID_SPRITE_JASON_BIG_IDLE + 10)
#define ID_SPRITE_JASON_BIG_IDLE_RIGHT (ID_SPRITE_JASON_BIG_IDLE + 20)
#define ID_SPRITE_JASON_BIG_IDLE_UP (ID_SPRITE_JASON_BIG_IDLE + 30)
#define ID_SPRITE_JASON_BIG_IDLE_DOWN (ID_SPRITE_JASON_BIG_IDLE + 40)
#define ID_SPRITE_JASON_BIG_WALK (ID_SPRITE_JASON_BIG + 200)
#define ID_SPRITE_JASON_BIG_WALK_UP (ID_SPRITE_JASON_BIG_WALK + 30)
#define ID_SPRITE_JASON_BIG_WALK_DOWN (ID_SPRITE_JASON_BIG_WALK + 40)
#define ID_SPRITE_JASON_BIG_WALK_RIGHT (ID_SPRITE_JASON_BIG_WALK + 20)
#define ID_SPRITE_JASON_BIG_WALK_LEFT (ID_SPRITE_JASON_BIG_WALK + 10)
#define ID_SPRITE_JASON_BIG_DASH (ID_SPRITE_JASON_BIG + 300)
#define ID_SPRITE_JASON_BIG_DASH_DOWN (ID_SPRITE_JASON_BIG_DASH + 10)
//die
#define ID_SPRITE_JASON_DIE (ID_SPRITE_JASON + 3000)
//small
#define ID_SPRITE_JASON_SMALL (ID_SPRITE_JASON + 2000)
#define ID_SPRITE_JASON_SMALL_IDLE (ID_SPRITE_JASON_SMALL + 100)
#define ID_SPRITE_JASON_SMALL_IDLE_LEFT (ID_SPRITE_JASON_SMALL_IDLE + 10)
#define ID_SPRITE_JASON_SMALL_IDLE_RIGHT (ID_SPRITE_JASON_SMALL_IDLE + 20)

#define ID_SPRITE_JASON_SMALL_WALKING (ID_SPRITE_JASON_SMALL + 200)
#define ID_SPRITE_JASON_SMALL_WALKING_LEFT (ID_SPRITE_JASON_SMALL_WALKING + 10)
#define ID_SPRITE_JASON_SMALL_WALKING_RIGHT (ID_SPRITE_JASON_SMALL_WALKING + 20)
#define ID_SPRITE_JASON_SMALL_RUNNING (ID_SPRITE_JASON_SMALL + 300)
#define ID_SPRITE_JASON_SMALL_RUNNING_LEFT (ID_SPRITE_JASON_SMALL_RUNNING + 10)
#define ID_SPRITE_JASON_SMALL_RUNNING_RIGHT (ID_SPRITE_JASON_SMALL_RUNNING + 20)
#define ID_SPRITE_JASON_SMALL_JUMP (ID_SPRITE_JASON_SMALL + 400)
#define ID_SPRITE_JASON_SMALL_JUMP_WALK (ID_SPRITE_JASON_SMALL_JUMP + 10)
#define ID_SPRITE_JASON_SMALL_JUMP_WALK_LEFT (ID_SPRITE_JASON_SMALL_JUMP_WALK + 2)
#define ID_SPRITE_JASON_SMALL_JUMP_WALK_RIGHT (ID_SPRITE_JASON_SMALL_JUMP_WALK + 6)
#define ID_SPRITE_JASON_SMALL_JUMP_RUN (ID_SPRITE_JASON_SMALL_JUMP + 20)
#define ID_SPRITE_JASON_SMALL_JUMP_RUN_LEFT (ID_SPRITE_JASON_SMALL_JUMP_RUN + 2)
#define ID_SPRITE_JASON_SMALL_JUMP_RUN_RIGHT (ID_SPRITE_JASON_SMALL_JUMP_RUN + 6)

#define ID_SPRITE_JASON_SMALL_SIT (ID_SPRITE_JASON_SMALL + 500)
#define ID_SPRITE_JASON_SMALL_SIT_LEFT (ID_SPRITE_JASON_SMALL_SIT + 10)
#define ID_SPRITE_JASON_SMALL_SIT_RIGHT (ID_SPRITE_JASON_SMALL_SIT + 20)

#define ID_SPRITE_JASON_SMALL_BRACE (ID_SPRITE_JASON_SMALL + 500)
#define ID_SPRITE_JASON_SMALL_BRACE_LEFT (ID_SPRITE_JASON_SMALL_BRACE + 10)
#define ID_SPRITE_JASON_SMALL_BRACE_RIGHT (ID_SPRITE_JASON_SMALL_BRACE + 20)
#pragma region enermy1
#define ID_SPRITE_BLACKFOOT 20000
#define ID_SPRITE_BLACKFOOT_WALKING_LEFT (ID_SPRITE_BLACKFOOT+1000)
#define ID_SPRITE_BLACKFOOT_WALKING_RIGHT (ID_SPRITE_BLACKFOOT+2000)
#define ID_SPRITE_BLACKFOOT_DIE (ID_SPRITE_BLACKFOOT+3000)

#define ID_SPRITE_SUNAMI 30000
#define ID_SPRITE_SUNAMI_IDLE (ID_SPRITE_SUNAMI+100)
#define ID_SPRITE_SUNAMI_WALKING_LEFT (ID_SPRITE_SUNAMI+1000)
#define ID_SPRITE_SUNAMI_WALKING_RIGHT (ID_SPRITE_SUNAMI+2000)
#define ID_SPRITE_SUNAMI_WALKING_UP (ID_SPRITE_SUNAMI+3000)
#define ID_SPRITE_SUNAMI_WALKING_DOWN (ID_SPRITE_SUNAMI+4000)
#define ID_SPRITE_SUNAMI_DIE (ID_SPRITE_SUNAMI+5000)

#define ID_SPRITE_EYELET 40000
#define ID_SPRITE_EYELET_FLYING_LEFT (ID_SPRITE_EYELET+1000)
#define ID_SPRITE_EYELET_FYLING_RIGHT (ID_SPRITE_EYELET+2000)
#define ID_SPRITE_EYELET_DIE (ID_SPRITE_EYELET+3000)

#define ID_SPRITE_BELLBOMBER 50000
#define ID_SPRITE_BELLBOMBER_FLYING_LEFT (ID_SPRITE_BELLBOMBER+1000)
#define ID_SPRITE_BELLBOMBER_FLYING_RIGHT (ID_SPRITE_BELLBOMBER+2000)
#define ID_SPRITE_BELLBOMBER_DROPPING_BOMB (ID_SPRITE_BELLBOMBER+3000)
#define ID_SPRITE_BELLBOMBER_DIE (ID_SPRITE_BELLBOMER+4000)